// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyDXYASC9gSmNNb6AH4ZzrKvk4MW_Mxrc',
    appId: '1:307443059663:web:4562c5c78add06bde8e0ba',
    messagingSenderId: '307443059663',
    projectId: 'localloop-ae85a',
    authDomain: 'localloop-ae85a.firebaseapp.com',
    storageBucket: 'localloop-ae85a.firebasestorage.app',
    measurementId: 'G-6FGSGBR18T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHfyOjMeMdWdI8gGNlR79j1J6eC8Jnqs',
    appId: '1:307443059663:android:0fe09b376ee131e3e8e0ba',
    messagingSenderId: '307443059663',
    projectId: 'localloop-ae85a',
    storageBucket: 'localloop-ae85a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQgCNdWdw_IQStkEvW5acCUc1NgZpFvQ',
    appId: '1:307443059663:ios:6d65f1be74092264e8e0ba',
    messagingSenderId: '307443059663',
    projectId: 'localloop-ae85a',
    storageBucket: 'localloop-ae85a.firebasestorage.app',
    iosBundleId: 'com.example.localLoop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUQgCNdWdw_IQStkEvW5acCUc1NgZpFvQ',
    appId: '1:307443059663:ios:6d65f1be74092264e8e0ba',
    messagingSenderId: '307443059663',
    projectId: 'localloop-ae85a',
    storageBucket: 'localloop-ae85a.firebasestorage.app',
    iosBundleId: 'com.example.localLoop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyDXYASC9gSmNNb6AH4ZzrKvk4MW_Mxrc',
    appId: '1:307443059663:web:266bbc4bde3b5ef5e8e0ba',
    messagingSenderId: '307443059663',
    projectId: 'localloop-ae85a',
    authDomain: 'localloop-ae85a.firebaseapp.com',
    storageBucket: 'localloop-ae85a.firebasestorage.app',
    measurementId: 'G-ZYKBQL5DCP',
  );

}